spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.13.253:3306/sell?characterEncoding=UTF-8&userSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect
#  return non_null
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.13.253
    port: 6379

server:
  context-path: /sell
  port: 8080

wechat:
  mpAppId: wxd898fcb01713c658
  myAppId: wxf14bf9b7d6a0f4d0
  mpAppSecret: c9fa4d34f8d7a54f7575e5926ae590d1
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: E:\h5.p12
  notifyUrl: http://cookie.natapp1.cc/sell/pay/notify
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e

project_url:
  wechatMpAuthorize: http://cookie.natapp1.cc/sell/wechat/userInfo
  wechatOpenAuthorize: http://cookie.natapp1.cc/sell/wechat/qrUserInfo
  login: http://cookie.natapp1.cc/sell/seller/login
  sell: http://cookie.natapp1.cc